### ISSUE TITLE
Stylování vizitky

### ISSUE THREAD

**Issue by thed3er** [anna-janikova/PROJEKT-Vizitka#1]
Ahoj Anno, super práce. Jsou tam drobnosti, které jsou potřeba opravit/dodělat:
- Velikost textu v tlačítkách není nastavena
- Odsazení mezi odstavci by nemělo být 30px.
- Text v odstavcích by měl být zarovnán do bloků

Jinak super práce. Jen tak dál :muscle:

**Comment by anna-janikova** [comment]
Ahoj,

tak jsem to konečně upravila. 

Nastavila jsem velikost textu tlačítka na 18px, 
pomocí vlastnosti margin jsem upravila odsazení mezi odstavci, teď je tam 10px, 
text jsem zarovnala do bloku.

Díky moc za trpělivost a za Tvoje poznámky. 

Anička
